/* bee2evp_err.c */
/* ====================================================================
 * Copyright (c) 1999-2011 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.OpenSSL.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@OpenSSL.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.OpenSSL.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

/* NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include "bee2evp_err.h"

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

#define ERR_FUNC(func) ERR_PACK(0,func,0)
#define ERR_REASON(reason) ERR_PACK(0,0,reason)

static ERR_STRING_DATA BEE2EVP_str_functs[]=
	{
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_DP2PARAMS),	"BIGN_ASN1_DP2PARAMS"},
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_ECP2GROUP),	"BIGN_ASN1_ECP2GROUP"},
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_ECP2PARAMS),	"BIGN_ASN1_ECP2PARAMS"},
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_PARAMETERS2GROUP),	"BIGN_ASN1_PARAMETERS2GROUP"},
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_PARAMS2CURVE),	"BIGN_ASN1_PARAMS2CURVE"},
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_PARAMS2DP),	"BIGN_ASN1_PARAMS2DP"},
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_PARAMS2ECP),	"BIGN_ASN1_PARAMS2ECP"},
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_PARAMS2FIELDID),	"BIGN_ASN1_PARAMS2FIELDID"},
{ERR_FUNC(BEE2EVP_F_BIGN_ASN1_PKPARAMETERS2GROUP),	"BIGN_ASN1_PKPARAMETERS2GROUP"},
{ERR_FUNC(BEE2EVP_F_BIGN_D2I_DOMAINPARAMS),	"BIGN_D2I_DOMAINPARAMS"},
{ERR_FUNC(BEE2EVP_F_BIGN_I2D_DOMAINPARAMS),	"BIGN_I2D_DOMAINPARAMS"},
{ERR_FUNC(BEE2EVP_F_BIGN_I2O_PUBKEY),	"BIGN_I2O_PUBKEY"},
{ERR_FUNC(BEE2EVP_F_BIGN_O2I_PUBKEY),	"BIGN_O2I_PUBKEY"},
{0,NULL}
	};

static ERR_STRING_DATA BEE2EVP_str_reasons[]=
	{
{ERR_REASON(BEE2EVP_R_ASN1_ERROR)        ,"asn1 error"},
{ERR_REASON(BEE2EVP_R_D2I_PARAMS_FAILURE),"d2i params failure"},
{ERR_REASON(BEE2EVP_R_DP2PARAMS_FAILURE) ,"dp2params failure"},
{ERR_REASON(BEE2EVP_R_I2D_PARAMS_FAILURE),"i2d params failure"},
{ERR_REASON(BEE2EVP_R_INVALID_FIELD)     ,"invalid field"},
{ERR_REASON(BEE2EVP_R_INVALID_GROUP_ORDER),"invalid group order"},
{ERR_REASON(BEE2EVP_R_INVALID_PUBKEY)    ,"invalid pubkey"},
{ERR_REASON(BEE2EVP_R_PARAMS2DP_FAILURE) ,"params2dp failure"},
{ERR_REASON(BEE2EVP_R_PARAMS_NEW_BY_NAME_FAILURE),"params new by name failure"},
{0,NULL}
	};

#endif

#ifdef BEE2EVP_LIB_NAME
static ERR_STRING_DATA BEE2EVP_lib_name[]=
        {
{0	,BEE2EVP_LIB_NAME},
{0,NULL}
	};
#endif


static int BEE2EVP_lib_error_code=0;
static int BEE2EVP_error_init=1;

void ERR_load_BEE2EVP_strings(void)
	{
	if (BEE2EVP_lib_error_code == 0)
		BEE2EVP_lib_error_code=ERR_get_next_error_library();

	if (BEE2EVP_error_init)
		{
		BEE2EVP_error_init=0;
#ifndef OPENSSL_NO_ERR
		ERR_load_strings(BEE2EVP_lib_error_code,BEE2EVP_str_functs);
		ERR_load_strings(BEE2EVP_lib_error_code,BEE2EVP_str_reasons);
#endif

#ifdef BEE2EVP_LIB_NAME
		BEE2EVP_lib_name->error = ERR_PACK(BEE2EVP_lib_error_code,0,0);
		ERR_load_strings(0,BEE2EVP_lib_name);
#endif
		}
	}

void ERR_unload_BEE2EVP_strings(void)
	{
	if (BEE2EVP_error_init == 0)
		{
#ifndef OPENSSL_NO_ERR
		ERR_unload_strings(BEE2EVP_lib_error_code,BEE2EVP_str_functs);
		ERR_unload_strings(BEE2EVP_lib_error_code,BEE2EVP_str_reasons);
#endif

#ifdef BEE2EVP_LIB_NAME
		ERR_unload_strings(0,BEE2EVP_lib_name);
#endif
		BEE2EVP_error_init=1;
		}
	}

void ERR_BEE2EVP_error(int function, int reason, char *file, int line)
	{
	if (BEE2EVP_lib_error_code == 0)
		BEE2EVP_lib_error_code=ERR_get_next_error_library();
	ERR_PUT_error(BEE2EVP_lib_error_code,function,reason,file,line);
	}
