/* ====================================================================
 * Copyright (c) 2001-2011 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@openssl.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

#ifndef HEADER_BEE2EVP_ERR_H
#define HEADER_BEE2EVP_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
void ERR_load_BEE2EVP_strings(void);
void ERR_unload_BEE2EVP_strings(void);
void ERR_BEE2EVP_error(int function, int reason, char *file, int line);
#define BEE2EVPerr(f,r) ERR_BEE2EVP_error((f),(r),__FILE__,__LINE__)

/* Error codes for the BEE2EVP functions. */

/* Function codes. */
#define BEE2EVP_F_BIGN_ASN1_DP2PARAMS			 100
#define BEE2EVP_F_BIGN_ASN1_ECP2GROUP			 101
#define BEE2EVP_F_BIGN_ASN1_ECP2PARAMS			 102
#define BEE2EVP_F_BIGN_ASN1_PARAMETERS2GROUP		 103
#define BEE2EVP_F_BIGN_ASN1_PARAMS2CURVE		 104
#define BEE2EVP_F_BIGN_ASN1_PARAMS2DP			 105
#define BEE2EVP_F_BIGN_ASN1_PARAMS2ECP			 106
#define BEE2EVP_F_BIGN_ASN1_PARAMS2FIELDID		 107
#define BEE2EVP_F_BIGN_ASN1_PKPARAMETERS2GROUP		 108
#define BEE2EVP_F_BIGN_D2I_DOMAINPARAMS			 109
#define BEE2EVP_F_BIGN_I2D_DOMAINPARAMS			 110
#define BEE2EVP_F_BIGN_I2O_PUBKEY			 111
#define BEE2EVP_F_BIGN_O2I_PUBKEY			 112

/* Reason codes. */
#define BEE2EVP_R_ASN1_ERROR				 100
#define BEE2EVP_R_D2I_PARAMS_FAILURE			 101
#define BEE2EVP_R_DP2PARAMS_FAILURE			 102
#define BEE2EVP_R_I2D_PARAMS_FAILURE			 103
#define BEE2EVP_R_INVALID_FIELD				 104
#define BEE2EVP_R_INVALID_GROUP_ORDER			 105
#define BEE2EVP_R_INVALID_PUBKEY			 106
#define BEE2EVP_R_PARAMS2DP_FAILURE			 107
#define BEE2EVP_R_PARAMS_NEW_BY_NAME_FAILURE		 108

#ifdef  __cplusplus
}
#endif
#endif
